import type { Metadata } from 'next'
import { headers } from 'next/headers'
import { Inter } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Providers } from './providers'
import { ClerkProvider } from '../lib/clerk-ui'
import './globals.css'

const inter = Inter({ subsets: ['latin'], display: 'swap' })

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://blogai.com'),
  title: {
    default: 'Blog AI — Brand-Consistent AI Content',
    template: '%s | Blog AI',
  },
  description:
    'Train your brand voice, run repeatable SEO content workflows, and generate publish-ready drafts faster.',
  openGraph: {
    type: 'website',
    siteName: 'Blog AI',
    locale: 'en_US',
    title: 'Blog AI — Brand-Consistent AI Content',
    description:
      'Train your brand voice, run repeatable SEO content workflows, and generate publish-ready drafts faster.',
  },
  twitter: {
    card: 'summary_large_image',
  },
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const publishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY

  // Read the per-request nonce generated by middleware.ts.
  const headersList = await headers()
  const nonce = headersList.get('x-nonce') ?? undefined

  // Inline script to prevent FOUC on dark mode.
  // Static string with no user input; nonce authorises it under the CSP.
  const themeScript =
    "(function(){try{var t=localStorage.getItem('theme');" +
    "if(t==='dark'||(t!=='light'&&matchMedia('(prefers-color-scheme:dark)').matches))" +
    "{document.documentElement.classList.add('dark')}}catch(e){}})()"

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script nonce={nonce} dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className={inter.className}>
        {publishableKey ? (
          <ClerkProvider publishableKey={publishableKey}>
            <Providers>{children}</Providers>
          </ClerkProvider>
        ) : (
          <Providers>{children}</Providers>
        )}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}
