name: org-release-please

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions: read-all

jobs:
  release-please:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: gr8monk3ys/github/.github/workflows/reusable-release-please.yml@f5ea73a3d864afd83314aa96ea37306c0a0f16e1
