name: org-precommit

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  precommit:
    uses: gr8monk3ys/github/.github/workflows/reusable-precommit.yml
