name: org-precommit

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  precommit:
    uses: gr8monk3ys/github/.github/workflows/reusable-precommit.yml@d9ca981dc738b842497fb293a8bf5ee3ee9beb34
