name: org-osv

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  osv:
    uses: gr8monk3ys/github/.github/workflows/reusable-osv.yml@f5ea73a3d864afd83314aa96ea37306c0a0f16e1
