name: org-release-please

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions: read-all

jobs:
  release-please:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: gr8monk3ys/github/.github/workflows/reusable-release-please.yml@77dc97653c1c78b3df82df3a18c4061ddfce666d
