name: org-gitleaks

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  gitleaks:
    uses: gr8monk3ys/github/.github/workflows/reusable-gitleaks.yml
